Objects:
  - object_name: Cube
    object_id: 0
    object_scale: 0.2
    object_position: [-1,0,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [0]
    resource_graphics_pipeline_id: 0
  - object_name: Cube
    object_id: 1
    object_scale: 0.2
    object_position: [1,0,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [0]
    resource_graphics_pipeline_id: 0
  - object_name: Cube
    object_id: 2
    object_scale: 0.2
    object_position: [0,-1,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [0]
    resource_graphics_pipeline_id: 0
  - object_name: Cube
    object_id: 3
    object_scale: 0.2
    object_position: [0,1,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [0]
    resource_graphics_pipeline_id: 0
  - object_name: Cube
    object_id: 4
    object_scale: 0.2
    object_position: [0,0,-1]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [0]
    resource_graphics_pipeline_id: 0
  - object_name: Cube
    object_id: 5
    object_scale: 0.2
    object_position: [0,0,1]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [0]
    resource_graphics_pipeline_id: 0
  - object_name: Cube
    object_id: 6
    object_scale: 0.2
    object_position: [0,0,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [10,10,10]
    object_skybox: false
    resource_model_id: 0
    resource_texture_id_list: [0]
    resource_graphics_pipeline_id: 0
  - object_name: SkyCube
    object_id: 7
    object_scale: 1
    object_position: [0,0,0]
    object_rotation: [0,0,0]
    object_velocity: [0,0,0]
    object_angular_velocity: [0,0,0]
    object_skybox: true
    resource_model_id: 0
    resource_texture_id_list: [0]
    resource_graphics_pipeline_id: 1

Resources:
  - Models:
    - resource_model_name: cube.obj
  - Textures:
    - resource_texture_name: skybox_interstellar.jpg
      resource_texture_miplevels: 1
      resource_texture_cubmap: true
      uniform_Sampler_id: 0
  - VertexShaders:
    - resource_vertexshader_name: simpleEnvironmentmap/environmentmap.vert.spv
    - resource_vertexshader_name: simpleEnvironmentmap/skybox.vert.spv
  - FragmentShaders:
    - resource_fragmentshader_name: simpleEnvironmentmap/environmentmap.frag.spv
    - resource_fragmentshader_name: simpleEnvironmentmap/skybox.frag.spv

Uniforms:
  - Graphics:
    - uniform_graphics_name: Graphics
      uniform_graphics_custom: true
      uniform_graphics_mvp: true
      uniform_graphics_vp: false
  - Compute:
    - uniform_compute_name: Compute
      uniform_compute_custom: false
      uniform_compute_storage: false
      uniform_compute_swapchain_storage: false
      uniform_compute_texture_storage: false
  - Samplers:
    - uniform_sampler_name: Sampler
      uniform_sampler_miplevel: 1

Features:
  feature_graphics_depth_test: true
  feature_graphics_msaa: false
  feature_graphics_48pbt: false
  feature_graphics_push_constant: false
  feature_graphics_blend: false
  feature_graphics_rainbow_mipmap: false
  feature_graphics_pipeline_skybox_id: 1


MainCamera:
  FreeMode: true
  Position: [0,0,-3]
  Rotation: [0,0,0]
  TargetLocation: [0,0,0]
  FOV: 60
  Z: [0.01, 256]

Lighting:
  Position: []
  Intensity: []

  